[package]
name = "arzhomeremodeling3243/bizbranches"
version = "0.1.0"
description = "Migrated Next.js Directory App"

[[app.storage]]
volume = "public-html"
path = "/out"

[app]
source = "wasmer/static-web-server-accelerated"

[app.env]
SERVER_ROOT = "/out"
